<?php
/**
 * Created by PhpStorm.
 * User: szl4zsy
 * Date: 4/10/2017
 * Time: 5:39 PM
 */
class userInfo extends userReg {
    public $step='1';
    public function stepNext($user)
    {
        if($user==null){
            $user=new userEntity();
            $user->username=$_POST['username'];
            $user->password=$_POST['password'];
            $_SESSION['user']=json_encode($user);
        }
        $get_user=parent::stepNext($user); // TODO: Change the autogenerated stub

    }
}